apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testtest
    spec:
      containers:
      - name: testtest
        image: gcr.io/${PROJECT_ID}/testtest:${REVISION_ID}
        ports:
        - containerPort: 8080
        env:
          - name: TESTTEST_MY_WEBAPP_PORT
            value: "8080"
          - name: TESTTEST_EXAMPLE_PORT
            value: "8000"
